baseURL = "davidandjulia.github.io"
languageCode = "en-us"
title = "Julia and David"
theme = "grayscale"
#googleAnalytics = ""
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
    # Provide some metadata for search and indexing services
    description = "David and Julia wedding"

[Author]
    name = "David Lilien and Julia Kelson"
    email = "julia.and.david.202something@gmail.com"
